# 베이스 이미지로 OpenJDK 17과 Gradle을 포함하는 이미지 사용
FROM gradle:jdk17 AS build

# 소스코드 복사
COPY . /app
WORKDIR /app

# Gradle을 사용하여 빌드
RUN gradle clean build

# 런타임 이미지
FROM openjdk:17
WORKDIR /app

# 빌드된 JAR 파일을 런타임 이미지에 복사
COPY --from=build /app/build/libs/Dotori-0.0.1-SNAPSHOT.jar /app/

# 애플리케이션 실행 명령어 설정
CMD ["java", "-jar", "/app/Dotori-0.0.1-SNAPSHOT.jar"]