version: "3"
services:
  dotori-user-service:
    image: bangjinseong/dotori-user-service:${BUILD_NUMBER}
    build:
      context: ../Dotori/backend/Dotori-User-Service
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER
    ports:
      - "9110:9110"
    environment:
      - SPRING_REDIS_HOST=redis
      - ENCRYPT_KEY=${ENCRYPT_KEY_VALUE}
      - TZ=Asia/Seoul
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "9050:6379"
    volumes:
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
